name: Rust-Build

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - run: |
          cargo build --release && 
          mv ./target/${{ matrix.target }}/release/restls ./target/${{ matrix.target }}/release/restls-${{ matrix.target }}
      - name: Upload Github Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.gh_upload }}
        with:
          files: target/${{ matrix.target }}/release/restls-${{ matrix.target }}
          prerelease: ${{ contains(github.ref, '-') }}
